---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "🌍 Translations"
    labels:
      - "translations"
  - title: "⬆️ Dependency updates"
    collapse-after: 5
    labels:
      - "dependencies"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "performance"
      - "refactor"
      - "translations"
  default: patch

template: |
  Enjoying Spook? 👻 A ⭐ on [GitHub](https://github.com/frenck/spook) lets others know Spook is actually pretty great. [Sponsoring Frenck](https://github.com/sponsors/frenck) keeps this ghost well fed. And his free bi-weekly [newsletter](https://frenck.dev/newsletter/) keeps your inner ghost well fed.

  # 👻👻👻👻👻👻👻👻👻👻

  Release notes go here.

  ../Frenck

  <p>
    <a href="https://www.linkedin.com/in/frenck/"><img src="https://github.com/frenck/frenck/raw/main/images/linkedin.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://youtube.com/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/youtube.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://bsky.app/profile/frenck.social"><img src="https://github.com/frenck/frenck/raw/main/images/bluesky.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://fosstodon.org/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/mastodon.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://www.instagram.com/frenck/"><img src="https://github.com/frenck/frenck/raw/main/images/instagram.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://www.threads.net/@frenck"><img src="https://github.com/frenck/frenck/raw/main/images/threads.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://www.facebook.com/frenck.dev/"><img src="https://github.com/frenck/frenck/raw/main/images/facebook.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://x.com/frenck"><img src="https://github.com/frenck/frenck/raw/main/images/x.svg" width="18" height="18"></a>
    &nbsp;&nbsp;
    <a href="https://www.tiktok.com/@frenck.nl"><img src="https://github.com/frenck/frenck/raw/main/images/tiktok.svg" width="18" height="18"></a>
  </p>

  Blogging my personal ramblings at <a href="https://frenck.dev">frenck.dev</a>
  Or subscribe to my bi-weekly newsletter: https://frenck.dev/newsletter

  # 👻👻👻👻👻👻👻👻👻👻

  $CHANGES

  # 👻👻👻👻👻👻👻👻👻👻
