"""Rebuild the reference files of Spook's agent skill.

The skill tells an agent what Spook offers without it reading the whole
documentation. Everything in the references comes from the files Home
Assistant itself reads, so they are generated rather than written, and a test
fails when somebody adds an action and forgets to run this.

Run it from anywhere, with the project's environment:

    uv run python script/generate_skill.py
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
from pathlib import Path
import re
from typing import Any

import yaml

ROOT = Path(__file__).parents[1]
SPOOK = ROOT / "custom_components" / "spook"
DOCS = ROOT / "documentation"
REFERENCES = ROOT / "plugins" / "spook" / "skills" / "spook" / "references"

GENERATED = (
    "<!-- Generated by script/generate_skill.py from Spook's source. "
    "Do not edit by hand. -->"
)

# Each entry on the reference pages of the documentation is the name in
# backticks, followed somewhere on the same line by the page explaining it.
_DOCUMENTED = re.compile(
    r"^`(?P<name>[a-z_]+\.[a-z_]+)`.*\[documentation\]\((?P<link>[^)]+)\)",
    re.MULTILINE,
)

# Paragraphs every repair opens or closes with, that say nothing about it.
_BOILERPLATE = (
    "Spook has found a ghost",
    "While floating around",
    "Spook 👻 Your homie.",
)


def _load_repair_documentation() -> tuple[str, dict[str, str]]:
    """Return where the documentation lives, and the page for each repair.

    The module is loaded straight from its file. Importing it the normal way
    drags in the whole integration, and with it Home Assistant, for one dict.
    """
    path = SPOOK / "repair_documentation.py"
    spec = importlib.util.spec_from_file_location("repair_documentation", path)
    if spec is None or spec.loader is None:
        msg = f"Cannot load {path}"
        raise ImportError(msg)

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.DOCUMENTATION_URL, module.REPAIR_DOCUMENTATION


DOCUMENTATION_URL, REPAIR_DOCUMENTATION = _load_repair_documentation()


def _yaml(name: str) -> dict[str, Any]:
    """Return one of the YAML files Home Assistant reads Spook's things from."""
    return yaml.safe_load((SPOOK / name).read_text(encoding="utf-8")) or {}


def _translations() -> dict[str, Any]:
    """Return the English translations, where the readable text lives."""
    return json.loads((SPOOK / "translations" / "en.json").read_text(encoding="utf-8"))


def _url(reference: str) -> str:
    """Turn a link from the documentation into the address it ends up at.

    The site flattens the folders and turns underscores into hyphens, so
    `integrations/input_number#x` is served as `input-number#x`.
    """
    page, _, anchor = reference.partition("#")
    page = page.rsplit("/", 1)[-1].replace("_", "-")
    url = f"{DOCUMENTATION_URL}/{page}"
    return f"{url}#{anchor}" if anchor else url


def _documentation_links(page: str) -> dict[str, str]:
    """Return the documentation address of every entry on a reference page."""
    text = (DOCS / page).read_text(encoding="utf-8")
    return {match["name"]: _url(match["link"]) for match in _DOCUMENTED.finditer(text)}


def action_domains() -> list[str]:
    """Return the domains Spook adds actions to, longest first.

    `services.yaml` joins domain and action with an underscore, and plenty of
    domains have one of their own, so splitting the key needs to know the
    domains rather than guess at the first underscore.
    """
    return sorted(
        (
            path.name
            for path in (SPOOK / "ectoplasms").iterdir()
            if (path / "services").is_dir()
        ),
        key=len,
        reverse=True,
    )


def action_name(key: str, domains: list[str]) -> str:
    """Return the action a `services.yaml` key describes.

    Spook keys its own actions bare, and the ones it adds to another domain as
    `<domain>_<action>`, which is the reverse of `_service_schema_key` in
    `services.py`.
    """
    for domain in domains:
        if key.startswith(f"{domain}_"):
            return f"{domain}.{key.removeprefix(f'{domain}_')}"
    return f"spook.{key}"


def _flat(text: str) -> str:
    """Put text that was wrapped over several lines back on one."""
    return " ".join(text.split())


def _value(value: Any) -> str:
    """Return a value from the YAML the way it is written in YAML."""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _selector(selector: dict[str, Any] | None) -> str | None:
    """Describe what a field takes, briefly, from its selector."""
    if not selector:
        return None

    kind, config = next(iter(selector.items()))
    config = config or {}

    if kind == "select":
        values = [
            option["value"] if isinstance(option, dict) else option
            for option in config.get("options", [])
        ]
        described = "one of " + ", ".join(f"`{value}`" for value in values)
        return f"list, each {described}" if config.get("multiple") else described

    if kind == "number" and "min" in config and "max" in config:
        unit = config.get("unit_of_measurement")
        unit = f" {unit}" if unit else ""
        return f"number, {_value(config['min'])} to {_value(config['max'])}{unit}"

    if config.get("multiple"):
        return f"{kind}, one or a list"
    return kind


def _fields(described: dict[str, Any], translated: dict[str, Any]) -> list[str]:
    """Return one line per field: name, whether it is required, and what it is."""
    lines = []
    for name, specification in described.items():
        field = specification or {}
        text = translated.get(name, {})

        details = ["required" if field.get("required") else "optional"]
        if kind := _selector(field.get("selector")):
            details.append(kind)

        line = f"- `{name}` ({', '.join(details)})"
        if description := _flat(text.get("description", "")):
            line += f": {description}"
        if "default" in field:
            line += f" Default: `{_value(field['default'])}`."
        if "example" in field:
            line += f" Example: `{_value(field['example'])}`."
        lines.append(line)
    return lines


def _target(target: dict[str, Any] | None) -> str:
    """Describe what an entry can be pointed at."""
    filters = (target or {}).get("entity") or []
    if isinstance(filters, dict):
        filters = [filters]

    domains = [entity["domain"] for entity in filters if "domain" in entity]
    if not domains:
        return "Target: any entities, devices, areas, floors or labels."
    named = " or ".join(f"`{domain}`" for domain in domains)
    return f"Target: {named} entities, or the devices, areas, floors and labels holding them."


# What an action that hands back a response asks of whoever calls it. One
# that only answers fails when called without asking for the answer.
_RESPONSES = {
    "ONLY": "Response: always. Call it asking for the response, or it fails.",
    "OPTIONAL": "Response: on request.",
}
_Classes = dict[str, tuple[dict[str, str], list[str]]]


def _action_classes() -> _Classes:
    """Return every class in Spook with what it sets itself, and its bases.

    Read with `ast`, so the generator never imports Home Assistant. An action
    that says nothing itself about its name or its response takes what one
    of its bases says, like every `create` of a helper does.
    """
    classes: _Classes = {}
    for path in SPOOK.rglob("*.py"):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            own: dict[str, str] = {}
            for statement in node.body:
                if not isinstance(statement, ast.Assign):
                    continue
                for target in statement.targets:
                    if not isinstance(target, ast.Name):
                        continue
                    value = statement.value
                    if target.id == "service" and isinstance(value, ast.Constant):
                        own["service"] = str(value.value)
                    elif target.id == "supports_response" and isinstance(
                        value, ast.Attribute
                    ):
                        own["supports_response"] = value.attr
            bases = [
                ast.unparse(base).split("[", 1)[0].rsplit(".", 1)[-1]
                for base in node.bases
            ]
            # Every action module names its class SpookService, so those are
            # keyed by file, and the rest by name.
            key = str(path) if node.name == "SpookService" else node.name
            classes[key] = (own, bases)
    return classes


def _inherited(classes: _Classes, key: str, attribute: str) -> str | None:
    """Return what a class, or the nearest of its bases, sets an attribute to."""
    own, bases = classes.get(key, ({}, []))
    if attribute in own:
        return own[attribute]
    for base in bases:
        if (found := _inherited(classes, base, attribute)) is not None:
            return found
    return None


def action_responses() -> dict[str, str]:
    """Return how each action that answers hands its response back.

    The folder an action sits in is the domain it is registered on.
    """
    classes = _action_classes()
    responses: dict[str, str] = {}
    for module in sorted(SPOOK.glob("ectoplasms/*/services/*.py")):
        key = str(module)
        response = _inherited(classes, key, "supports_response")
        service = _inherited(classes, key, "service")
        if response in _RESPONSES and service:
            responses[f"{module.parent.parent.name}.{service}"] = response
    return responses


def _entry(  # noqa: PLR0913  # pylint: disable=too-many-arguments
    name: str,
    described: dict[str, Any],
    translated: dict[str, Any],
    fields_heading: str,
    *,
    documentation: str | None = None,
    response: str | None = None,
) -> list[str]:
    """Return the lines for one action, trigger or condition."""
    lines = [
        f"### `{name}`: {_flat(translated['name'])}",
        "",
        _flat(translated.get("description", "")),
        "",
    ]

    if response:
        lines += [_RESPONSES[response], ""]

    if "target" in described:
        lines += [_target(described["target"]), ""]

    if fields := described.get("fields"):
        lines += [
            f"{fields_heading}:",
            "",
            *_fields(fields, translated.get("fields", {})),
            "",
        ]

    if documentation:
        lines += [f"Documentation: {documentation}", ""]
    return lines


def _page(title: str, introduction: str, lines: list[str]) -> str:
    """Return a whole reference file."""
    return "\n".join([GENERATED, "", f"# {title}", "", introduction, "", *lines])


def render_actions() -> str:
    """Return the reference of every action Spook adds, grouped by domain."""
    described = _yaml("services.yaml")
    translated = _translations()["services"]
    links = _documentation_links("actions.md")
    domains = action_domains()
    responses = action_responses()

    by_name = {action_name(key, domains): key for key in described}

    lines: list[str] = []
    current = None
    for name in sorted(by_name):
        domain = name.split(".", 1)[0]
        if domain != current:
            lines += [f"## {domain}", ""]
            current = domain

        key = by_name[name]
        lines += _entry(
            name,
            described[key] or {},
            translated[key],
            "Data",
            documentation=links.get(name),
            response=responses.get(name),
        )

    return _page(
        "Spook actions",
        "Call these like any other action, as `domain.action`, with fields "
        "under `data:` and the target under `target:`. Many of them live on "
        "the domain they act on, not on `spook`.",
        lines,
    )


def _automation_reference(kind: str, introduction: str) -> str:
    """Return the reference for Spook's triggers or conditions."""
    described = _yaml(f"{kind}.yaml")
    translated = _translations()[kind]
    links = _documentation_links(f"{kind}.md")

    lines: list[str] = []
    for key in sorted(described):
        name = f"spook.{key}"
        lines += _entry(
            name,
            described[key] or {},
            translated[key],
            "Options",
            documentation=links.get(name),
        )
    return _page(f"Spook {kind}", introduction, lines)


def render_triggers() -> str:
    """Return the reference of every trigger Spook adds."""
    return _automation_reference(
        "triggers",
        "Use these in the new-style syntax: `trigger: spook.<name>`, with "
        "fields under `options:` and the target under `target:`.",
    )


def render_conditions() -> str:
    """Return the reference of every condition Spook adds."""
    return _automation_reference(
        "conditions",
        "Use these in the new-style syntax: `condition: spook.<name>`, with "
        "fields under `options:` and the target under `target:`.",
    )


def _meaning(description: str) -> str:
    """Return the first paragraph of a repair that says what it found.

    The ones around it are the greeting, the sign-off, and the lists that get
    filled in when the issue is raised.
    """
    for wrapped in description.split("\n\n"):
        paragraph = _flat(wrapped)
        if not paragraph or paragraph.startswith(_BOILERPLATE):
            continue

        # A paragraph of nothing but placeholders and links is a list.
        words = re.sub(r"\[[^\]]*\]\([^)]*\)|\{[a-z_]+\}|[`()\s:.,]", "", paragraph)
        if not words:
            continue

        # It introduces the list that follows, which is not here.
        if paragraph.endswith(":"):
            return f"{paragraph[:-1]}."
        return paragraph
    return "Its text is whatever the caller gave it."


def _repair_documentation(key: str) -> str | None:
    """Return the documentation for a repair, or for the one it is a variant of.

    A repair that words its issue differently depending on the house has a
    translation per wording, like `unknown_area_sensors_both`, while the
    documentation knows it by its own name.
    """
    for repair in sorted(REPAIR_DOCUMENTATION, key=len, reverse=True):
        if key == repair or key.startswith(f"{repair}_"):
            return f"{DOCUMENTATION_URL}/{REPAIR_DOCUMENTATION[repair]}"
    return None


def render_repairs() -> str:
    """Return one line for every kind of repair Spook can raise."""
    lines = []
    for key, issue in sorted(_translations()["issues"].items()):
        steps = issue.get("fix_flow", {}).get("step", {})
        first_step = next(iter(steps.values()), {})
        description = issue.get("description") or first_step.get("description", "")

        line = f'- `{key}`: "{issue["title"]}". {_meaning(description)}'
        if choices := first_step.get("menu_options"):
            line += f" Fix offers: {'; '.join(choices.values())}."
        elif steps:
            line += " Fixable."
        if documentation := _repair_documentation(key):
            line += f" Documentation: {documentation}"
        lines.append(line)

    return _page(
        "Spook repairs",
        "Every kind of issue Spook raises in Repairs, under the `spook` "
        "domain. An issue ID starts with the key below (or the start of it, "
        "for the keys that only word the same repair differently, like "
        "`_yaml`), followed by what it was found in. Text in braces is filled "
        "in when the issue is raised.",
        [*lines, ""],
    )


def render() -> dict[str, str]:
    """Return every reference file, by file name."""
    return {
        "actions.md": render_actions(),
        "conditions.md": render_conditions(),
        "repairs.md": render_repairs(),
        "triggers.md": render_triggers(),
    }


def write(directory: Path) -> None:
    """Write every reference file into a directory."""
    directory.mkdir(parents=True, exist_ok=True)
    references = render()

    # A reference that is no longer made would linger, and the test that
    # holds the folder to what is made would keep failing after regenerating.
    # Only files this generator wrote, going by the line it starts them with:
    # pointed at the wrong folder, it must not take anybody's notes with it.
    for stale in directory.glob("*.md"):
        if stale.name not in references and stale.read_text(
            encoding="utf-8"
        ).startswith(GENERATED):
            stale.unlink()

    for name, content in references.items():
        (directory / name).write_text(content, encoding="utf-8")


def main() -> None:
    """Rebuild the references, in the skill or wherever asked."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output",
        type=Path,
        default=REFERENCES,
        help="directory to write the references to (default: the skill's own)",
    )
    write(parser.parse_args().output)


if __name__ == "__main__":
    main()
