---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
