---
name: Pylint

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: 🏗 Install dependencies
        run: uv sync --frozen --dev

      - name: 🚀 Run pylint
        run: uv run prek run pylint --all-files
