---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
