---
name: Zizmor

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: 🏗 Install dependencies
        run: uv sync --frozen --dev

      - name: 🚀 Run zizmor
        env:
          GH_TOKEN: ${{ github.token }}
        run: uv run zizmor .github/workflows/
